#define T_EMDROSLANG_KEY_STYLESHEET                   1
#define T_EMDROSLANG_KEY_FETCHINFO                    2
#define T_EMDROSLANG_KEY_XMLRENDERINFO                3
#define T_EMDROSLANG_IDENTIFIER                       4
#define T_EMDROSLANG_KEY_EXTENDS                      5
#define T_EMDROSLANG_KEY_NULL                         6
#define T_EMDROSLANG_KEY_FALSE                        7
#define T_EMDROSLANG_KEY_TRUE                         8
#define T_EMDROSLANG_KEY_MINUS                        9
#define T_EMDROSLANG_INTEGER                         10
#define T_EMDROSLANG_STRING                          11
#define T_EMDROSLANG_KEY_LBRACE                      12
#define T_EMDROSLANG_KEY_RBRACE                      13
#define T_EMDROSLANG_KEY_COMMA                       14
#define T_EMDROSLANG_KEY_COLON                       15
#define T_EMDROSLANG_KEY_LSQUARE_BRACKET             16
#define T_EMDROSLANG_KEY_RSQARE_BRACKET              17
#define T_EMDROSLANG_KEY_FUNCTION                    18
#define T_EMDROSLANG_KEY_LPAREN                      19
#define T_EMDROSLANG_KEY_RPAREN                      20
#define T_EMDROSLANG_KEY_COLON_COLON                 21
#define T_EMDROSLANG_KEY_VAR                         22
#define T_EMDROSLANG_KEY_SEMICOLON                   23
#define T_EMDROSLANG_KEY_ASSIGN                      24
#define T_EMDROSLANG_KEY_WHILE                       25
#define T_EMDROSLANG_KEY_DO                          26
#define T_EMDROSLANG_KEY_FOR                         27
#define T_EMDROSLANG_KEY_IN                          28
#define T_EMDROSLANG_KEY_IF                          29
#define T_EMDROSLANG_KEY_ELIF                        30
#define T_EMDROSLANG_KEY_ELSE                        31
#define T_EMDROSLANG_KEY_AND_AND                     32
#define T_EMDROSLANG_KEY_PIPE_PIPE                   33
#define T_EMDROSLANG_KEY_EQEQ                        34
#define T_EMDROSLANG_KEY_NEQ                         35
#define T_EMDROSLANG_KEY_GT                          36
#define T_EMDROSLANG_KEY_GEQ                         37
#define T_EMDROSLANG_KEY_LT                          38
#define T_EMDROSLANG_KEY_LEQ                         39
#define T_EMDROSLANG_KEY_PLUS                        40
#define T_EMDROSLANG_KEY_STAR                        41
#define T_EMDROSLANG_KEY_SLASH                       42
#define T_EMDROSLANG_KEY_PERCENT                     43
#define T_EMDROSLANG_KEY_NOT                         44
#define T_EMDROSLANG_KEY_RSQUARE_BRACKET             45
