#define T_TEMPLATELANG_KEY_ID_D                         1
#define T_TEMPLATELANG_KEY_FIRSTMONAD                   2
#define T_TEMPLATELANG_KEY_LASTMONAD                    3
#define T_TEMPLATELANG_KEY_FEATURE                      4
#define T_TEMPLATELANG_KEY_SPACE                        5
#define T_TEMPLATELANG_INTEGER                          6
#define T_TEMPLATELANG_KEY_BB_CLOSE                     7
#define T_TEMPLATELANG_KEY_FEATUREJSONMANGLE            8
#define T_TEMPLATELANG_KEY_FEATURENOMANGLE              9
#define T_TEMPLATELANG_KEY_DBNAME                      10
#define T_TEMPLATELANG_KEY_ATTRIB                      11
#define T_TEMPLATELANG_IDENTIFIER                      12
#define T_TEMPLATELANG_KEY_ATTRIB_NOMANGLE             13
#define T_TEMPLATELANG_KEY_COPYATTRIBS                 14
#define T_TEMPLATELANG_KEY_COUNTER                     15
#define T_TEMPLATELANG_STRING                          16
#define T_TEMPLATELANG_KEY_BARE_FORMAT                 17
#define T_TEMPLATELANG_KEY_SETCOUNTER                  18
#define T_TEMPLATELANG_KEY_BARE_VAR                    19
#define T_TEMPLATELANG_KEY_INCCOUNTER                  20
#define T_TEMPLATELANG_KEY_DECCOUNTER                  21
#define T_TEMPLATELANG_KEY_LISTEMIT                    22
#define T_TEMPLATELANG_KEY_LISTCLEAR                   23
#define T_TEMPLATELANG_KEY_NAMEDSETEMIT                24
#define T_TEMPLATELANG_KEY_NAMEDSETCLEAR               25
#define T_TEMPLATELANG_KEY_DICTLOOKUP                  26
#define T_TEMPLATELANG_KEY_BARE_FEATURE                27
#define T_TEMPLATELANG_KEY_BARE_FEATURENOMANGLE        28
#define T_TEMPLATELANG_KEY_BARE_VARNOMANGLE            29
#define T_TEMPLATELANG_KEY_BARE_COUNTER                30
#define T_TEMPLATELANG_KEY_SETNIXING_ALL               31
#define T_TEMPLATELANG_KEY_SETNIXING_DOC               32
#define T_TEMPLATELANG_KEY_SETNIXING_OFF               33
#define T_TEMPLATELANG_KEY_IF_FEATUREEQUAL             34
#define T_TEMPLATELANG_KEY_IF_VAREQUAL                 35
#define T_TEMPLATELANG_KEY_IF_LISTEMPTY                36
#define T_TEMPLATELANG_KEY_IF_NAMEDSETEMPTY            37
#define T_TEMPLATELANG_KEY_IF_HASATTRIB                38
#define T_TEMPLATELANG_KEY_IF_ATTRIBEQUAL              39
#define T_TEMPLATELANG_KEY_ENDIF                       40
#define T_TEMPLATELANG_KEY_ELSE                        41
#define T_TEMPLATELANG_KEY_LISTAPPENDBEGIN             42
#define T_TEMPLATELANG_KEY_LISTAPPENDEND               43
#define T_TEMPLATELANG_KEY_NAMEDSETADD                 44
#define T_TEMPLATELANG_KEY_NAMEDSETADDEND              45
#define T_TEMPLATELANG_KEY_NAMEDSETREMOVE              46
#define T_TEMPLATELANG_KEY_NAMEDSETREMOVEEND           47
#define T_TEMPLATELANG_KEY_SETVAR                      48
#define T_TEMPLATELANG_KEY_BARE_SUBSTRING              49
#define T_TEMPLATELANG_KEY_BARE_FROM                   50
#define T_TEMPLATELANG_KEY_BARE_MAXLENGTH              51
#define T_TEMPLATELANG_KEY_BARE_ATTRIB                 52
#define T_TEMPLATELANG_KEY_BARE_ATTRIBNOMANGLE         53
#define T_TEMPLATELANG_KEY_BARE_FEATUREJSONMANGLE      54
#define T_TEMPLATELANG_KEY_SETVAREND                   55
#define T_TEMPLATELANG_KEY_EMITVAR                     56
#define T_TEMPLATELANG_CHAR                            57
#define T_TEMPLATELANG_KEY_BARE_TO                     58
#define T_TEMPLATELANG_KEY_DASH                        59
#define T_TEMPLATELANG_KEY_NEWLINE                     60
